# database related options
db:
  provider: mysql
  host: 127.0.0.1
  port: 3306
  database: meertrap
  user:
    name: meertrap
    password: "XXX"
  root:
    name: root
    password: "XXX"
  users:
    - name: meertrap
      password: "XXX"
    - name: meertrap_ro
      password: "XXX"
  databases:
    - name: meertrap
    - name: production
    - name: old

# filesystem related options
filesystem:
  ingest:
    staging_dir: /data/staging
    processed_dir: /data/processed
  webserver:
    candidate_dir: /webserver
