# database related options
db:
  provider: mysql
  host: 127.0.0.1
  port: 3306
  database: meertrap_test
  user:
    name: meertrap
    password: "XXX"
  root:
    name: root
    password: "XXX"
  users:
    - name: meertrap
      password: "XXX"
    - name: meertrap_ro
      password: "XXX"
  databases:
    - name: meertrap
    - name: production
    - name: old

# filesystem related options
filesystem:
  ingest:
    staging_dir: /data/staging
    glob_pattern: "2*/tpn*/2*.spccl.log"
    processed_dir: /data/processed
  sb_info:
    filename: schedule_block.json
    version: 1
  summary_file:
    glob_pattern: '*_run_summary.json'
  date_formats:
    utc: "%Y-%m-%d_%H:%M:%S"
    local: "%Y-%m-%d %H:%M:%S.%f"
  webserver:
    candidate_dir: /webserver

# candidate file related options
candidates:
  version: 2

# multibeam sifter related options
sifter:
  # time threshold for matching in milliseconds
  time_thresh: 10.0
  # fractional DM tolerance
  dm_thresh: 0.02

# known source matching related options
knownsources:
  # distance threshold in degress
  dist_thresh: 1.5
  # fractional dm threshold in percent
  dm_thresh: 5.0

# slack notifier related options
notifier:
  http_link: XXX
  colour: "#37961d"
